import subprocess
import os
import tempfile
import sys
import re


class SandboxExecutor:
    """Runs Python code generated by agents in a sandboxed subprocess."""

    def __init__(self, timeout=5):
        self.timeout = timeout

    def run_code(self, code):
        if not code or ("def " not in code and "print" not in code):
            return False, "No executable code found."

        with tempfile.NamedTemporaryFile(suffix=".py", mode="w", delete=False) as tmp:
            tmp.write(code)
            tmp_path = tmp.name

        try:
            result = subprocess.run(
                [sys.executable, tmp_path],
                capture_output=True,
                text=True,
                timeout=self.timeout,
            )
            if result.returncode == 0:
                return True, result.stdout.strip()
            else:
                return False, result.stderr.strip()
        except subprocess.TimeoutExpired:
            return False, "Execution Timeout (Possible Infinite Loop)"
        except Exception as e:
            return False, str(e)
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    def extract_code(self, text):
        """Extracts Python code from Markdown blocks."""
        pattern = r"```python(.*?)```"
        matches = re.findall(pattern, text, re.DOTALL)
        return "\n".join(matches).strip() if matches else text.strip()


if __name__ == "__main__":
    executor = SandboxExecutor()
    test_code = "print(sum([1, 2, 3]))"
    success, output = executor.run_code(test_code)
    print(f"Test Execution: Success={success}, Output={output}")
